#!/bin/bash

# Cocon-caravan (midori) launcher

if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ -z $COCON_WWW_START ];
then
  COCON_WWW_START="http://www.opencocon.org/"
fi


# Just run midori
exec midori -p $COCON_WWW_START

