#!/bin/bash

USERN=/tmp/.cocon.menu.usern


# opencocon FreeRDP Launcher
if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ -z $COCON_RDP_RDPFILE ];
then
  if [ -z $COCON_RDP_HOST ];
  then
    echo "Error: please spcify COCON_RDP_HOST."
    exit 1
  else

    # User name
    if [ -z $COCON_RDP_USER ];
    then
      dialog --inputbox "Enter login username (require for login)" 8 40 2>$USERN
      COCON_RDP_USER="`cat $USERN`"
    fi

    OPTION="$OPTION -u $COCON_RDP_USER "

    # Domain name
    if [ $COCON_RDP_DOMAIN ];
    then
      OPTION="$OPTION -d $COCON_RDP_DOMAIN "
    fi

   # TODO : password

  fi

else
  # .rdp file is present: ignore COCON_RDP_HOST etc.
#  OPTION="$OPTION $COCON_RDP_RDPFILE "
  echo "WARNING: RDPFILE is disabled."
fi


# Remote FX
if [ "$COCON_RDP_RFX" = "1" ];
then
  OPTION="$OPTION --rfx --plugin drdynvc --data tsmf -- --plugin --data audin -- "
fi


#if [ "$COCON_RDP_MODEM" = "1" ];
#then
#  OPTION="$OPTION -x modem "
#fi

# finally, add HOSTNAME
OPTION="$OPTION $COCON_RDP_HOST "

while :
do

  echo "=========================================="
  echo "    PASSWORD is not shown in console."
  echo "=========================================="

  xfreerdp -f -x 81 --plugin rdpsnd --data alsa -- $OPTION
  retr=$?

  if [ "$retr" != "131" ];
  then
    break
  fi
done

# echo "Current return : $retr" > /var/volatile/log/cocon-freerdp.log
# sleep 5

