#!/bin/bash

# opencocon main menu

SELECT=/tmp/.cocon.menu.select
HOSTN=/tmp/.cocon.menu.host
USERN=/tmp/.cocon.menu.usern
DOMAIN=/tmp/.cocon.menu.domain
PWROFF=/tmp/.cocon.poweroff
PORTN=/tmp/.cocon.port
PORTN2=/tmp/.cocon.port2
SSH_HOSTN=/tmp/.cocon.sshhost
SSH_PORT=/tmp/.cocon.sshport
SSH_USERN=/tmp/.cocon.sshuser
SSH_FWHOSTN=/tmp/.cocon.fwhost
SSH_FWPORT=/tmp/.cocon.fwport
ABOUT=/usr/share/doc/cocon/about.txt
VERSION=/etc/cocon-version
PARTCNF=/tmp/.cocon.cnf.part

dialog --no-cancel --menu "`cat $VERSION` (experimental)" 20 40 25 \
XEPHYR "Connect XDMCP" \
RDP "Connect RDP" \
VNC2 "Connect VNC" \
VNC "Connect VNC (Alt.)" \
SPICE "Connect SPICE" \
WWW "Web Browser" \
NET "Network Setting" \
SSHPF "Setup SSH port forwarding" \
ETC "Option, Ambient tools" \
ABOUT "About opencocon" \
OFF "Power Off" 2>$SELECT

select=`cat $SELECT`

case $select in 
XEPHYR)

  # XDMCP via XEPHYR

  dialog --inputbox "Enter hostname to connect" 8 40 2>$HOSTN
  
  hostn=`cat $HOSTN`
  rm $HOSTN
  if [ $hostn ];
  then
    echo "COCON_X_HOST=$hostn" >> $PARTCNF
    cocon-xephyr-launch
    rm $PARTCNF
  fi
  ;;


VNC)

  # Connect VNC via gtk-vnc (Alt.)

  dialog --inputbox "Enter hostname:display to connect" 8 40 2>$HOSTN
  hostn=`cat $HOSTN`
  echo "COCON_VNC_HOST=$hostn" >> $PARTCNF
  echo "COCON_VNC_GTK-VNC=1" >> $PARTCNF

  cocon-vnc-launch
  rm $PARTCNF
  ;;

VNC2)
   
  # Connect VNC via libvncclient 

  dialog --inputbox "Enter hostname:display to connect" 8 40 2>$HOSTN
  hostn=`cat $HOSTN`
  echo "COCON_VNC_HOST=$hostn" >> $PARTCNF

  cocon-vnc-launch
  rm $PARTCNF
  ;;


RDP)

  # Connect RDP with xfreerdp

  dialog --inputbox "Enter hostname(:port) to connect" 8 40 2>$HOSTN
  dialog --inputbox "Enter login username" 8 40 2>$USERN

  hostn=`cat $HOSTN`
  usern=`cat $USERN`
 
  if [ $usern ];
  then
    dialog --inputbox "Enter Domain name (if not use domain name, just enter)" 8 40 2>$DOMAIN
    rdpdomain=`cat $DOMAIN`
  fi

  if [ $hostn ];
  then
    echo "COCON_RDP_HOST=$hostn" >> $PARTCNF

    if [ $usern ];
    then
      echo "COCON_RDP_USER=$usern" >> $PARTCNF
    fi

    if [ $rdpdomain ];
    then
      echo "COCON_RDP_DOMAIN=$rdpdomain" >> $PARTCNF
    fi

    cocon-freerdp-launch
    
    rm $PARTCNF
  fi
  
  ;;

SPICE)

  # SPICE

  dialog --inputbox "Enter hostname to connect" 8 40 2>$HOSTN
  hostn=`cat $HOSTN`
  
  if [ $hostn ];
  then
    echo "COCON_SPICE_HOST=$hostn" >> $PARTCNF
  
    dialog --inputbox "Enter port number (non-TLS, default is 5900)" 8 40 2>$PORTN
    dialog --inputbox "Enter port number (TLS, default is 5901)" 8 40 2>$PORTN2
 
    echo "COCON_SPICE_PORT=`cat $PORTN`" >> $PARTCNF
    echo "COCON_SPICE_TLSPORT=`cat $PORTN2`" >> $PARTCNF

    cocon-spice-launch

    rm $PARTCNF

    # Workaround: force restart lxterminal.
    pkill lxterminal
  fi

  ;;

SSHPF)
  dialog --inputbox "Enter SSH hostname to connect" 8 40 2>$SSH_HOSTN
  dialog --inputbox "Enter SSH port to connect (if default port(22), just enter)" 8 40 2>$SSH_PORT
  dialog --inputbox "Enter SSH username" 8 40 2>$SSH_USERN
  dialog --inputbox "Enter forward hostname" 8 40 2>$SSH_FWHOSTN
  dialog --inputbox "Enter forward port (RDP:3389, VNC:5900+Display number)" 8 40 2>$SSH_FWPORT
  
  ssh_hostn=`cat $SSH_HOSTN`
  ssh_port=`cat $SSH_PORT`
  ssh_user=`cat $SSH_USERN`
  ssh_fwhostn=`cat $SSH_FWHOSTN`
  ssh_fwport=`cat $SSH_FWPORT`
  
  if [ -n "$ssh_hostn" -a -n "$ssh_user" -a -n "$ssh_fwhostn" -a -n "$ssh_fwport" ];
  then
    if [ -z "$ssh_port" ];
    then
      ssh_port=22 
    fi

    # TODO : move to sepalated script
    /usr/bin/ssh -N -f -L $ssh_fwport:$ssh_fwhostn:$ssh_fwport -p $ssh_port -l $ssh_user $ssh_hostn
  
    if [ -z "`pidof ssh`" ];
    then
      dialog --msgbox "Failed to connect." 15 60
    else
      dialog --msgbox "Okey, SSH port-forwarding is connected. please input hostname to 'localhost'." 15 60
    fi
  fi
  ;;

WWW)
  # Web Browser
  cocon-caravan-launch
  ;;

NET)
  cocon-netset-launch
  ;;

ETC)
  # Sub menu
  cocon-option-menu
  ;;


ABOUT)
  about=`cat $ABOUT`
  dialog --msgbox "$about" 20 60
  ;;

OFF)
  # Power-off flag (to cocon-menu)
  touch $PWROFF
  exit 1

  ;;

esac

