#!/bin/sh

BOOT_ROOT=
ROOT_DEVICE=

early_setup() {
    mkdir -p /proc /sys /mnt /tmp /target

    mount -t proc proc /proc
    mount -t sysfs sysfs /sys
}

dev_setup() {
    mdev -s
    cat < /mdev_path > /proc/sys/kernel/hotplug
}

do_depmod() {
	[ -e "/lib/modules/$(uname -r)/modules.dep" ] || depmod -a
}

fatal() {
    echo $1 >$CONSOLE
    echo >$CONSOLE
    exec sh
}

echo "Starting coconfd:"
early_setup
do_depmod

[ -z "$CONSOLE" ] && CONSOLE="/dev/console"

dev_setup

# Load Japanese jp106 Keymap
loadkeys jp106

# FAT module
modprobe vfat

echo " "
echo "opencocon v3(alpha) hyper-experimental boot floppy"
echo "Developed by SHIMADA Hirofumi <shimadah@hus.osaka-u.ac.jp>"
echo "More Information, http://opencocon.org/"
echo "If you need USB device support, run /usb"
echo "++ Welcome to mystery world, enjoy! ++"
echo " "

exec sh

sync
sync
sync

fatal
