#!/bin/bash

# opencocon userland init

# special machines
rm /etc/X11/xorg.conf.d/*
/usr/bin/cocon-spmachine


# Run Menu
su -c 'cocon-startx' xuser
retr=$?

# Power off runs on .profile!
cocon-poweroff

