#!/bin/bash

# opencocon power-off script

if [ `echo $COCON_DEBUG` ];
then
  echo "DEBUG: before shutdown. Maybe X.org failed."
  /bin/sh
fi


if [ -z "$BOOT_FS" ];
then
  # Direct-boot
  modprobe apm power_off=1
  /sbin/poweroff
else
  # Stop udev
  /etc/init.d/udev stop
  pkill udevd
  # have union-boot flag
  cd /media/cf
  exec ./clean <dev/console >dev/console 2>&1
fi


