#!/bin/bash

# opencocon Xephyr launcher
if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ $COCON_X_HOST ];
then
  # XDMCP via Xephyr
  exec Xephyr -query $COCON_X_HOST -fullscreen -once :1
else
  echo "Please specify HOST."
fi

