#!/bin/bash

# opencocon power-off script

if [ -z "$BOOT_FS" ];
then
  # Direct-boot
  modprobe apm power_off=1
  /sbin/poweroff
else
  # have union-boot flag
  cd /media/cf
  exec ./clean <dev/console >dev/console 2>&1
fi


