#!/bin/bash

# opencocon FreeRDP Launcher
if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ -z $COCON_RDP_RDPFILE ];
then
  if [ -z $COCON_RDP_HOST ];
  then
    echo "Error: please spcify COCON_RDP_HOST."
    exit 1
  else
    OPTION="$OPTION /v:$COCON_RDP_HOST "

    # User name
    if [ $COCON_RDP_USER ];
    then
      OPTION="$OPTION /u:$COCON_RDP_USER "
    fi
    # TODO : if empty, Prompt user name! 

    # Domain name
    if [ $COCON_RDP_DOMAIN ];
    then
      OPTION="$OPTION /d:$COCON_RDP_DOMAIN "
    fi

   # TODO : password

  fi

else
  # .rdp file is present: ignore COCON_RDP_HOST etc.
  OPTION="$OPTION $COCON_RDP_RDPFILE "
fi


# Remote FX
if [ "$COCON_RDP_RFX" = "1" ];
then
  OPTION="$OPTION /rfx /multimedia:sys:alsa /microphone:sys:alsa "
fi

while :
do

  # TODO : Show message : Password prompt is shown neither string or *!

  xfreerdp $OPTION /f -wallpaper -themes +fonts /sound:sys:alsa /audio-mode
  retr=$?

  if [ "$retr" != "131" ];
  then
    break
  fi
done

echo "Current return : $retr"    
sleep 5

