#!/bin/bash

# opencocon userland init

# Run Menu

menu_flag=`cat /proc/cmdline | grep noxmenu`

if [ "$menu_flag" ];
then
  # noxmenu mode : Classic menu
  su -c 'cocon-menu-launch' xuser
  retr=$?
else
  # Modern X
  su -c 'cocon-startx' xuser
  retr=$?
fi

# Power off runs on .profile!
cocon-poweroff

