#!/bin/bash

# first, copy settings from skel.
cp -R /etc/skel/.config/ /home/xuser
cp /etc/skel/.profile /home/xuser
cp /etc/skel/.xinitrc /home/xuser 

# Workaround for radeon bugs:
if [ "` lsmod | grep radeon`" ];
then
  X_OPTION="-- -depth 24"
fi

if [ "` lsmod | grep savage`" ];
then
  X_OPTION="-- -depth 24"
fi



# opencocon userland startx
startx $X_OPTION
retr=$?

echo "X.org return: $retr"

if [ $retr -ne 0 ];
then
  # Error on wakeup X
  dialog --msgbox "Xorg initalize was failed. please try 'forcefb1', 'forcefb2' and 'forcefb3' option on boot loader." 20 60
  echo "To reboot, input 'exit'."
  /bin/sh
  exit 1
fi

exit 0
