#!/bin/bash

# opencocon VNC Launcher

if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ $COCON_VNC_HOST ];
then
    
  if [ "`echo $COCON_VNC_GTK-VNC`" = "1" ];
  then
    # gtk-vnc
    exec gvncviewer $COCON_VNC_HOST
  else
    # libvncviewer
    exec gtkvncviewer $COCON_VNC_HOST
  fi
 
else
  echo "Please specify HOST."
fi

